apiVersion: v1
description: Bookinfo Productpage Service Helm Chart
name: bookinfo-reviews
version: 1.0.0
appVersion: 1.0.0
# metadata
home: http://productpage.big-bookinfo.opsta.in.th/ais/ratings/
maintainers:
  - name: Opsta Developer
    email: sathtawut@opsta.in.th
source:
  - https: https://gitlab.com/workshop35/bookinfo/productpage